import { generateId } from '../lib/crypto.js';
import {
  users,
  workspaces,
  workspaceMembers,
  projects,
  repositories,
  agents,
  agentTasks,
  agentEvents,
  approvalRequests,
  permissionPolicies,
  providerConfigs,
  devices,
  deployments,
  usageRecords,
  notifications,
  auditEvents,
} from './schema/index.js';

export interface SeedData {
  user: typeof users.$inferSelect;
  workspace: typeof workspaces.$inferSelect;
  projects: (typeof projects.$inferSelect)[];
  agents: (typeof agents.$inferSelect)[];
  tasks: (typeof agentTasks.$inferSelect)[];
  events: (typeof agentEvents.$inferSelect)[];
  approvals: (typeof approvalRequests.$inferSelect)[];
  permissions: (typeof permissionPolicies.$inferSelect)[];
  providers: (typeof providerConfigs.$inferSelect)[];
  devices: (typeof devices.$inferSelect)[];
  deployments: (typeof deployments.$inferSelect)[];
  usage: typeof usageRecords.$inferSelect;
  notifications: (typeof notifications.$inferSelect)[];
  auditLog: (typeof auditEvents.$inferSelect)[];
}

const userId = 'usr_satyam_99';
const workspaceId = 'ws_satyam_01';
const projectId = 'proj_bambookit_web';
const agentId = 'agent_backend_sonnet';
const taskId = 'task_auth_google_01';

export const INITIAL_SEED_DATA: SeedData = {
  user: {
    id: userId,
    email: 'satyampote9999@gmail.com',
    passwordHash: '$2a$10$abcdefghijklmnopqrstuvwxyz1234567890', // placeholder bcrypt
    name: 'Satyam Pote',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    createdAt: new Date('2026-08-15T10:00:00Z'),
    updatedAt: new Date('2026-08-15T10:00:00Z'),
  },
  workspace: {
    id: workspaceId,
    name: "Satyam's Workspace",
    slug: 'satyams-workspace',
    ownerId: userId,
    tier: 'PRO',
    createdAt: new Date('2026-08-15T10:00:00Z'),
    updatedAt: new Date('2026-08-15T10:00:00Z'),
  },
  projects: [
    {
      id: projectId,
      workspaceId,
      repositoryId: 'repo_bambookit_web',
      name: 'BambooKit Web',
      slug: 'bambookit-web',
      description: 'Next.js 15 production console and developer control plane UI.',
      executionMode: 'HYBRID',
      defaultBranch: 'main',
      status: 'ACTIVE',
      createdAt: new Date('2026-08-20T08:00:00Z'),
      updatedAt: new Date('2026-09-22T03:15:00Z'),
    },
    {
      id: 'proj_bambookit_api',
      workspaceId,
      repositoryId: 'repo_bambookit_api',
      name: 'BambooKit API',
      slug: 'bambookit-api',
      description: 'Hono / Node.js agent orchestration server and real-time control gateway.',
      executionMode: 'CLOUD',
      defaultBranch: 'main',
      status: 'ACTIVE',
      createdAt: new Date('2026-08-22T14:30:00Z'),
      updatedAt: new Date('2026-09-21T18:40:00Z'),
    },
    {
      id: 'proj_payment_gateway',
      workspaceId,
      repositoryId: null,
      name: 'Payment Gateway',
      slug: 'payment-gateway',
      description: 'Stripe & Razorpay webhook processor with zero-trust key isolation.',
      executionMode: 'CLOUD',
      defaultBranch: 'develop',
      status: 'ACTIVE',
      createdAt: new Date('2026-09-01T11:20:00Z'),
      updatedAt: new Date('2026-09-20T09:12:00Z'),
    },
    {
      id: 'proj_docs_portal',
      workspaceId,
      repositoryId: null,
      name: 'Docs Portal',
      slug: 'docs-portal',
      description: 'Comprehensive product and architectural documentation repository.',
      executionMode: 'LOCAL',
      defaultBranch: 'main',
      status: 'ACTIVE',
      createdAt: new Date('2026-09-05T16:00:00Z'),
      updatedAt: new Date('2026-09-19T20:30:00Z'),
    },
  ],
  agents: [
    {
      id: agentId,
      workspaceId,
      projectId,
      name: 'Backend Agent',
      description: 'Specialized in fullstack TypeScript, API routes, database schemas, and auth flows.',
      agentType: 'CODING',
      provider: 'ANTHROPIC',
      model: 'claude-3-7-sonnet-20250219',
      status: 'WAITING_FOR_APPROVAL',
      executionMode: 'CLOUD',
      permissionPolicyId: 'pol_default',
      createdAt: new Date('2026-08-21T09:00:00Z'),
      updatedAt: new Date('2026-09-22T03:22:00Z'),
    },
    {
      id: 'agent_frontend_gemini',
      workspaceId,
      projectId,
      name: 'Frontend Agent',
      description: 'Next.js UI, responsive design system, Tailwind components, and client reactivity.',
      agentType: 'CODING',
      provider: 'GOOGLE',
      model: 'gemini-2.5-pro',
      status: 'RUNNING',
      executionMode: 'CLOUD',
      permissionPolicyId: 'pol_default',
      createdAt: new Date('2026-08-21T09:00:00Z'),
      updatedAt: new Date('2026-09-22T03:25:00Z'),
    },
    {
      id: 'agent_refactor_codex',
      workspaceId,
      projectId: 'proj_bambookit_api',
      name: 'Refactor Agent',
      description: 'Code cleanup, strict typing improvements, dead-code pruning, and performance auditing.',
      agentType: 'REFACTORING',
      provider: 'OPENAI',
      model: 'gpt-4.5-preview',
      status: 'IDLE',
      executionMode: 'CLOUD',
      permissionPolicyId: 'pol_default',
      createdAt: new Date('2026-08-23T10:00:00Z'),
      updatedAt: new Date('2026-09-21T18:40:00Z'),
    },
    {
      id: 'agent_doc_local',
      workspaceId,
      projectId: 'proj_docs_portal',
      name: 'Documentation Agent',
      description: 'Maintains API references, markdown changelogs, architecture diagrams, and guides.',
      agentType: 'DOCUMENTATION',
      provider: 'OLLAMA',
      model: 'qwen-2.5-coder-32b',
      status: 'IDLE',
      executionMode: 'LOCAL',
      permissionPolicyId: 'pol_default',
      createdAt: new Date('2026-09-06T11:00:00Z'),
      updatedAt: new Date('2026-09-19T20:30:00Z'),
    },
  ],
  tasks: [
    {
      id: taskId,
      workspaceId,
      projectId,
      agentId,
      title: 'Add Google authentication and session callback flow',
      prompt:
        'Add Google authentication to our Next.js application, fix the signup flow, run test suites, commit the changes and prepare for production deployment.',
      status: 'WAITING_FOR_APPROVAL',
      executionMode: 'CLOUD',
      branch: 'feat/google-auth',
      commitSha: '8f31c2a',
      startedAt: new Date('2026-09-22T03:10:00Z'),
      completedAt: null,
      error: null,
      createdAt: new Date('2026-09-22T03:10:00Z'),
      updatedAt: new Date('2026-09-22T03:13:10Z'),
    },
  ],
  events: [
    {
      id: 'evt_001',
      workspaceId,
      projectId,
      agentId,
      taskId,
      type: 'agent.started',
      summary: 'Task initialized in isolated cloud worker container',
      payload: { command: 'git checkout -b feat/google-auth' },
      severity: 'INFO',
      actor: 'AGENT',
      timestamp: new Date('2026-09-22T03:10:02Z'),
    },
    {
      id: 'evt_002',
      workspaceId,
      projectId,
      agentId,
      taskId,
      type: 'agent.file_changed',
      summary: 'Modified src/lib/auth.ts to add Google OAuth provider & JWT callback',
      payload: { additions: 46, deletions: 12, file: 'src/lib/auth.ts' },
      severity: 'INFO',
      actor: 'AGENT',
      timestamp: new Date('2026-09-22T03:11:04Z'),
    },
    {
      id: 'evt_003',
      workspaceId,
      projectId,
      agentId,
      taskId,
      type: 'agent.test_finished',
      summary: '24 tests passed across 4 test suites (0 failures)',
      payload: { passed: 24, failed: 0, durationMs: 1240 },
      severity: 'INFO',
      actor: 'AGENT',
      timestamp: new Date('2026-09-22T03:12:35Z'),
    },
    {
      id: 'evt_004',
      workspaceId,
      projectId,
      agentId,
      taskId,
      type: 'agent.approval_requested',
      summary: 'Approval requested: Deploy commit 8f31c2a to Production',
      payload: { approvalId: 'appr_deploy_prod_01', action: 'Deploy to Production', risk: 'HIGH' },
      severity: 'WARN',
      actor: 'AGENT',
      timestamp: new Date('2026-09-22T03:13:10Z'),
    },
  ],
  approvals: [
    {
      id: 'appr_deploy_prod_01',
      workspaceId,
      projectId,
      agentId,
      taskId,
      action: 'Deploy to Production',
      riskLevel: 'HIGH',
      scope: 'ONCE',
      reason:
        'All 24 authentication unit and integration tests passed. The agent requests authorization to trigger production deployment and update live DNS.',
      resources: [
        'Production Kubernetes Cluster (us-east-1)',
        'Live Edge CDN (Cloudflare)',
        'Database Migration (users table schema addition)',
      ],
      status: 'PENDING',
      details: {
        command: 'bambookit-deploy --env=production --ref=8f31c2a',
        files: ['src/app/api/auth/[...nextauth]/route.ts', 'src/lib/auth.ts'],
        environment: 'Production (Live)',
      },
      requestedAt: new Date('2026-09-22T03:13:10Z'),
      expiresAt: new Date('2026-09-23T03:13:10Z'),
      resolvedAt: null,
      resolvedById: null,
    },
  ],
  permissions: [
    {
      id: 'pol_fs',
      workspaceId,
      name: 'Filesystem Access',
      category: 'FILESYSTEM',
      state: 'ALLOWED',
      rules: ['Restricted to project root'],
      createdAt: new Date('2026-08-15T10:00:00Z'),
      updatedAt: new Date('2026-08-15T10:00:00Z'),
    },
    {
      id: 'pol_prod',
      workspaceId,
      name: 'Production Deployment & Rollback',
      category: 'PRODUCTION',
      state: 'APPROVAL_REQUIRED',
      rules: ['Requires human authorization'],
      createdAt: new Date('2026-08-15T10:00:00Z'),
      updatedAt: new Date('2026-08-15T10:00:00Z'),
    },
    {
      id: 'pol_secrets',
      workspaceId,
      name: 'Environment Secrets',
      category: 'SECRETS',
      state: 'APPROVAL_REQUIRED',
      rules: ['Masked in logs', 'Never sent plaintext to LLM'],
      createdAt: new Date('2026-08-15T10:00:00Z'),
      updatedAt: new Date('2026-08-15T10:00:00Z'),
    },
  ],
  providers: [
    {
      id: 'prov_anthropic',
      workspaceId,
      provider: 'ANTHROPIC',
      name: 'Anthropic Claude',
      baseUrl: 'https://api.anthropic.com',
      defaultModel: 'claude-3-7-sonnet-20250219',
      encryptedApiKey: 'encrypted_placeholder',
      keyIv: 'iv_placeholder',
      keyTag: 'tag_placeholder',
      enabled: true,
      createdAt: new Date('2026-08-15T10:00:00Z'),
      updatedAt: new Date('2026-08-15T10:00:00Z'),
    },
    {
      id: 'prov_openai',
      workspaceId,
      provider: 'OPENAI',
      name: 'OpenAI',
      baseUrl: 'https://api.openai.com/v1',
      defaultModel: 'gpt-4.5-preview',
      encryptedApiKey: 'encrypted_placeholder',
      keyIv: 'iv_placeholder',
      keyTag: 'tag_placeholder',
      enabled: true,
      createdAt: new Date('2026-08-15T10:00:00Z'),
      updatedAt: new Date('2026-08-15T10:00:00Z'),
    },
  ],
  devices: [
    {
      id: 'dev_android_satyam',
      workspaceId,
      userId,
      name: "Satyam's Pixel 9 Pro (Android)",
      type: 'ANDROID',
      status: 'ONLINE',
      version: 'BambooKit Android v0.9.4',
      publicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...',
      lastSeenAt: new Date('2026-09-22T03:30:00Z'),
      ipAddressMasked: '103.21.***.45',
      createdAt: new Date('2026-08-16T12:00:00Z'),
      updatedAt: new Date('2026-09-22T03:30:00Z'),
    },
    {
      id: 'dev_desktop_win',
      workspaceId,
      userId,
      name: 'Workstation-Win11 (Desktop Connector)',
      type: 'WINDOWS_DESKTOP',
      status: 'ONLINE',
      version: 'BambooKit Connector v0.8.2',
      publicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI...',
      lastSeenAt: new Date('2026-09-22T03:28:00Z'),
      ipAddressMasked: '192.168.***.12',
      createdAt: new Date('2026-08-16T12:00:00Z'),
      updatedAt: new Date('2026-09-22T03:28:00Z'),
    },
  ],
  deployments: [
    {
      id: 'dep_prod_109',
      workspaceId,
      projectId,
      environment: 'PRODUCTION',
      commitSha: '8f31c2a',
      commitMessage: 'feat(auth): integrate google oauth & session callback',
      status: 'READY',
      url: 'https://bambookit.dev',
      durationSeconds: 42,
      deployedByAgentId: agentId,
      createdAt: new Date('2026-09-22T03:15:00Z'),
      updatedAt: new Date('2026-09-22T03:15:42Z'),
    },
  ],
  usage: {
    id: 'usg_2026_09',
    workspaceId,
    projectId,
    agentId,
    provider: 'ANTHROPIC',
    model: 'claude-3-7-sonnet-20250219',
    inputTokens: 1200000,
    outputTokens: 220500,
    estimatedCostUsd: '21.30',
    workerSeconds: 14820,
    storageBytes: 1488977920, // ~1.4GB
    timestamp: new Date('2026-09-22T03:00:00Z'),
  },
  notifications: [
    {
      id: 'notif_1',
      workspaceId,
      userId,
      type: 'APPROVAL_REQUIRED',
      title: 'Approval Required: Deploy to Production',
      body: 'Backend Agent finished auth integration and requested live deployment.',
      read: false,
      link: '/approvals',
      metadata: { taskId, approvalId: 'appr_deploy_prod_01' },
      createdAt: new Date('2026-09-22T03:13:10Z'),
    },
  ],
  auditLog: [
    {
      id: 'aud_001',
      workspaceId,
      actorType: 'AGENT',
      actorId: agentId,
      actorName: 'Backend Agent (Sonnet 3.7)',
      action: 'Requested Deployment Approval',
      resourceType: 'APPROVAL',
      resourceId: 'appr_deploy_prod_01',
      metadata: { ref: '8f31c2a', environment: 'PRODUCTION' },
      ipAddress: '10.0.4.12',
      createdAt: new Date('2026-09-22T03:13:10Z'),
    },
  ],
};
